# Generated by Django 4.2.6 on 2023-10-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('destination_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('base_code', models.CharField(max_length=3, unique=True)),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
