# Generated by Django 4.2.6 on 2023-10-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='base_code',
            field=models.CharField(max_length=3),
        ),
    ]
